name: Qlik Community User Data
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: qlik-community-data.svg
          base: ""
          plugin_screenshot: yes
          plugin_screenshot_title: Qlik Community User Data
          plugin_screenshot_url: https://qlik-community-badges.vercel.app/?userId=124946&theme=dark
          plugin_screenshot_selector: "#app"
          plugin_screenshot_viewport: | 
              { "width": 1280, "height": 400 }
